### PR TITLE
chore: add security policy

### PR DESCRIPTION
**Pull request by coaxial**

### CODE REVIEW

**Comment by benjaminoakes** [comment]
Should we have a private email address too?

**Comment by coaxial** [comment]
I was considering it, but then went with issues instead. Do you think it'd be worth the overhead and have a more private way to report security issues?

I was also trying to come up with reasonable scenarios and since rules are written by the user, the kind of vulnerabilities we might be exposed to will likely be through third party dependencies only. We can't do much about these other than waiting for a patch, and dependabot would flag them automatically. 

But maybe I'm missing something obvious here, curious to hear your thoughts.

**Comment by benjaminoakes** [comment]
Those are good points.

I could easily make a maid-security@benjaminoakes.com group with both of us in it, in case someone finds a significant security vulnerability that we don't expect.  It might be nice to have a domain for Maid someday, but that may not make sense right now.

**Comment by benjaminoakes** [comment]
What do you think?  If you'd like, I can add that email address or we can continue discussing.

**Comment by coaxial** [comment]
Good idea!

**Comment by benjaminoakes** [comment]
Done!

**Comment by coaxial** [comment]
Thank you!

**Comment by benjaminoakes** [comment]
No problem! Quick and easy 🙂

**Pull request merged**
