### PR TITLE
Support passing scheduler options to Rufus

### PR DESCRIPTION
**Pull request by markprzepiora**
This allows you to do, e.g.,

```ruby
repeat '1s', overlap: false do
  # ...
end
```

so that your jobs don't run on top of each other.

### CODE REVIEW

**Comment by benjaminoakes** [comment]
@coaxial This PR would still seem to be valuable, but we need to make sure CI runs on it.

**Comment by coaxial** [comment]
Can we use a rebase instead of a merge?

**Comment by benjaminoakes** [comment]
> Can we use a rebase instead of a merge?

No problem with that.  :smile:   I guess GitHub is set to merge when I click the "update branch" button.

**Comment by benjaminoakes** [comment]
Hmm...  Will "squash and merge" negate the need for rebasing?

I'd like to merge and go through the motions of a RubyGems release so I can make sure I can properly transfer access to you.  I figured I would clean out the existing pull requests as a part of that.

**Review by benjaminoakes — APPROVED** [review]

**Pull request merged**
